import os
import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
from dotenv import load_dotenv
import json
from datetime import datetime

load_dotenv()

# --- LangChain Imports (Updated for Gemini) ---
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage


# -------------------------------------------------------------
# 1. INPUT & OUTPUT SCHEMAS
# -------------------------------------------------------------

class InsightsInput(BaseModel):
    """The raw financial data structure sent from Node.js."""
    insights: Dict[str, Any]


class FinancialInsightsOutput(BaseModel):
    """The structured financial analysis generated by Gemini."""
    
    spendingInsight: str = Field(description="Simple explanation about spending behaviour.")
    incomeInsight: str = Field(description="Simple explanation about income trends.")
    billInsight: str = Field(description="Upcoming bills or spending pressure.")
    riskLevel: str = Field(description="Low, Moderate, or High financial risk.")
    advice: str = Field(description="Actionable general advice.")
    summary: str = Field(description="One sentence summary of financial status.")
    recommendations: List[str] = Field(description="3-5 actionable improvement recommendations.")
    cashflowTips: List[str] = Field(description="3 practical cash flow management tips.")


# -------------------------------------------------------------
# 2. MODEL + APP INITIALIZATION
# -------------------------------------------------------------

app = FastAPI(
    title="CashFlow AI — Gemini Financial Advisor",
    description="Provides structured financial insights using Gemini + LangChain."
)

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.3,
    google_api_key=os.getenv("GOOGLE_API_KEY")
)


# -------------------------------------------------------------
# 3. PROMPT TEMPLATE
# -------------------------------------------------------------

PROMPT_TEMPLATE = """
You are a financial advisor AI for small business owners.
Analyze the provided financial DATA and generate helpful, actionable insights.

FINANCIAL DATA:
Current Month Expenses: ${currentMonthExpenses}
Average Monthly Expenses (last 3 months): ${averageExpenses}
Spending Increase: {percentageIncrease}%
Spending Too High: {isSpendingHigh}

Current Month Income: ${currentMonthIncome}
Average Monthly Income (last 3 months): ${averageIncome}
Income Decrease: {percentageDecrease}%
Income Too Low: {isInflowLow}

Upcoming Bills: {upcomingBills}

You MUST respond with valid JSON matching this EXACT structure:
{{
  "spendingInsight": "1-2 sentences explaining spending pattern and trends",
  "incomeInsight": "1-2 sentences explaining income pattern and trends",
  "billInsight": "Mention upcoming bills or note if none exist",
  "riskLevel": "Low or Moderate or High",
  "advice": "One short actionable recommendation for this month",
  "summary": "One sentence overall financial health summary",
  "recommendations": [
    "First specific actionable step to improve finances",
    "Second specific actionable step to improve finances",
    "Third specific actionable step to improve finances"
  ],
  "cashflowTips": [
    "First practical cash flow management tip",
    "Second practical cash flow management tip",
    "Third practical cash flow management tip"
  ]
}}

IMPORTANT RULES:
1. recommendations MUST contain 3-5 items (never empty)
2. cashflowTips MUST contain exactly 3 items (never empty)
3. Even if finances are healthy, provide tips for maintenance and growth
4. Be specific and actionable, avoid generic advice
5. Focus on small business cash flow management

Respond ONLY with valid JSON, no additional text before or after.
"""

prompt = ChatPromptTemplate.from_template(PROMPT_TEMPLATE)
ai_chain = prompt | llm


# -------------------------------------------------------------
# 4. ENDPOINTS
# -------------------------------------------------------------

@app.get("/")
async def root():
    return {
        "message": "CashFlow AI is running",
        "endpoints": {
            "POST /ai/insights": "Generate structured financial insights with Gemini",
            "POST /ai/chat": "Chat with financial advisor AI",
            "GET /health": "Health check"
        }
    }

@app.get("/health")
async def health_check():
    api_key_configured = bool(os.getenv("GOOGLE_API_KEY"))
    return {
        "status": "healthy",
        "api_key_configured": api_key_configured,
        "model": "gemini-2.5-flash"
    }


@app.post("/ai/insights", response_model=FinancialInsightsOutput)
async def generate_ai_insights(data: InsightsInput):
    try:
        insights = data.insights
        
        # Extract the key values for the prompt
        spending_data = insights.get("spendingTooHigh", {})
        inflow_data = insights.get("inflowsLow", {})
        upcoming_bills = insights.get("upcomingBills", [])
        
        # Format the prompt input
        prompt_input = {
            "currentMonthExpenses": spending_data.get("currentMonthExpenses", 0),
            "averageExpenses": spending_data.get("averageExpenses", 0),
            "percentageIncrease": round(spending_data.get("percentageIncrease", 0), 1),
            "isSpendingHigh": spending_data.get("isHigh", False),
            "currentMonthIncome": inflow_data.get("currentMonthIncome", 0),
            "averageIncome": inflow_data.get("averageIncome", 0),
            "percentageDecrease": round(inflow_data.get("percentageDecrease", 0), 1),
            "isInflowLow": inflow_data.get("isLow", False),
            "upcomingBills": json.dumps(upcoming_bills) if upcoming_bills else "None"
        }
        
        # Invoke the chain
        response = await ai_chain.ainvoke(prompt_input)
        
        # Parse JSON from response
        response_text = response.content
        
        # Remove markdown code blocks if present
        if "```json" in response_text:
            response_text = response_text.split("```json")[1].split("```")[0].strip()
        elif "```" in response_text:
            response_text = response_text.split("```")[1].split("```")[0].strip()
        
        response_dict = json.loads(response_text)
        
        # Validate and return
        response_object = FinancialInsightsOutput(**response_dict)
        return response_object

    except json.JSONDecodeError as e:
        print(f"JSON Parse Error: {e}")
        print(f"Response text: {response_text}")
        raise HTTPException(status_code=500, detail=f"Failed to parse AI response as JSON")
    except Exception as e:
        print("AI Error:", e)
        raise HTTPException(status_code=500, detail=f"AI inference failed: {str(e)}")


# -------------------------------------------------------------
# ENHANCED CHATBOT SCHEMAS
# -------------------------------------------------------------

class Transaction(BaseModel):
    """Transaction data for context"""
    type: str
    amount: float
    category: Optional[str] = None
    description: Optional[str] = None
    date: Optional[str] = None

class UserData(BaseModel):
    """User profile data"""
    name: Optional[str] = None
    currentBalance: Optional[float] = None
    currency: Optional[str] = "$"
    businessName: Optional[str] = None
    businessType: Optional[str] = None

class ChatContextRequest(BaseModel):
    """Enhanced chat request with full context"""
    userMessage: str = Field(description="The user's question or message")
    userData: Optional[UserData] = Field(default=None, description="User profile information")
    recentTransactions: List[Transaction] = Field(default=[], description="Recent transactions for context")
    conversationHistory: List[Dict[str, str]] = Field(default=[], description="Previous messages in conversation")

class ChatResponseEnhanced(BaseModel):
    """Enhanced chat response with suggestions"""
    response: str = Field(description="AI assistant's response")
    suggestions: List[str] = Field(default=[], description="Suggested follow-up questions")
    insights: Optional[Dict[str, Any]] = Field(default=None, description="Additional insights if applicable")


# -------------------------------------------------------------
# ENHANCED CHATBOT ENDPOINT
# -------------------------------------------------------------

@app.post("/ai/chat", response_model=ChatResponseEnhanced)
async def chat_with_financial_advisor(request: ChatContextRequest):
    """
    Enhanced chatbot that understands user context, transactions, and provides smart suggestions.
    """
    try:
        # Create chatbot LLM instance
        chat_llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            temperature=0.7,
            google_api_key=os.getenv("GOOGLE_API_KEY")
        )
        
        # Build comprehensive context
        user_info = ""
        if request.userData:
            user_data = request.userData.model_dump()
            user_info = f"""
USER PROFILE:
- Name: {user_data.get('name', 'User')}
- Business: {user_data.get('businessName', 'N/A')} ({user_data.get('businessType', 'N/A')})
- Current Balance: {user_data.get('currency', '$')}{user_data.get('currentBalance', 0):,.2f}
"""

        transactions_info = ""
        if request.recentTransactions:
            transactions_info = "\nRECENT TRANSACTIONS:\n"
            for i, txn in enumerate(request.recentTransactions[:5], 1):
                transactions_info += f"{i}. {txn.type.upper()}: {txn.description or txn.category} - ${txn.amount:,.2f} ({txn.date or 'recent'})\n"
        
        # System prompt with context
        system_prompt = f"""You are an expert financial advisor AI assistant specializing in small business cash flow management.

{user_info}
{transactions_info}

Your role:
1. Provide clear, actionable financial advice
2. Analyze spending patterns and identify opportunities
3. Answer questions about transactions, budgeting, and cash flow
4. Be conversational but professional
5. Use the user's actual data when providing insights

Guidelines:
- Be specific and use actual numbers from the context
- Avoid generic advice - tailor to the user's situation
- If asked about transactions, reference the recent ones provided
- If balance is low, mention it tactfully
- Celebrate wins when income is good or spending is controlled
- Use simple language, avoid jargon
"""

        # Build message history
        messages = [SystemMessage(content=system_prompt)]
        
        # Add conversation history (last 6 messages for context)
        for msg in request.conversationHistory[-6:]:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            if role == "user":
                messages.append(HumanMessage(content=content))
            elif role == "assistant":
                messages.append(AIMessage(content=content))
        
        # Add current user message
        messages.append(HumanMessage(content=request.userMessage))
        
        # Get AI response
        response = await chat_llm.ainvoke(messages)
        
        # Generate smart suggestions based on context
        suggestions = generate_suggestions(
            request.userMessage,
            request.userData,
            request.recentTransactions
        )
        
        # Extract insights if the request is about financial analysis
        insights = None
        if any(word in request.userMessage.lower() for word in ['spending', 'expenses', 'income', 'balance', 'how much']):
            insights = analyze_quick_insights(request.userData, request.recentTransactions)
        
        return ChatResponseEnhanced(
            response=response.content,
            suggestions=suggestions,
            insights=insights
        )
        
    except Exception as e:
        print("Chat Error:", e)
        raise HTTPException(status_code=500, detail=f"Chat failed: {str(e)}")


def generate_suggestions(message: str, user_data: Optional[UserData], transactions: List[Transaction]) -> List[str]:
    """Generate smart follow-up suggestions based on context"""
    
    message_lower = message.lower()
    suggestions = []
    
    if 'balance' in message_lower:
        suggestions.extend([
            "What are my biggest expenses this month?",
            "How can I improve my cash flow?",
            "Show me my income vs expenses"
        ])
    elif 'spend' in message_lower or 'expense' in message_lower:
        suggestions.extend([
            "Which category am I spending most on?",
            "How does this compare to last month?",
            "Give me tips to reduce expenses"
        ])
    elif 'income' in message_lower or 'revenue' in message_lower:
        suggestions.extend([
            "How can I increase my revenue?",
            "What's my profit margin?",
            "Show me income trends"
        ])
    elif any(word in message_lower for word in ['advice', 'help', 'improve', 'tips']):
        suggestions.extend([
            "Analyze my financial health",
            "What should I prioritize this month?",
            "Create a budget plan for me"
        ])
    else:
        if user_data and user_data.currentBalance is not None and user_data.currentBalance < 1000:
            suggestions.append("How can I improve my cash runway?")
        
        suggestions.extend([
            "What's my current financial status?",
            "Show recent transactions",
            "Give me cash flow tips"
        ])
    
    return suggestions[:5]


def analyze_quick_insights(user_data: Optional[UserData], transactions: List[Transaction]) -> Dict[str, Any]:
    """Quick financial insights from available data"""
    
    if not transactions:
        return None
    
    total_income = sum(t.amount for t in transactions if t.type == "income")
    total_expenses = sum(t.amount for t in transactions if t.type == "expense")
    
    insights = {
        "totalIncome": round(total_income, 2),
        "totalExpenses": round(total_expenses, 2),
        "netCashflow": round(total_income - total_expenses, 2),
        "transactionCount": len(transactions)
    }
    
    if user_data and user_data.currentBalance is not None:
        insights["currentBalance"] = user_data.currentBalance
        
        if total_expenses > 0:
            daily_burn = total_expenses / 30
            runway_days = int(user_data.currentBalance / daily_burn) if daily_burn > 0 else 999
            insights["runwayDays"] = runway_days
    
    return insights


# -------------------------------------------------------------
# 5. LOCAL RUN
# -------------------------------------------------------------
if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    uvicorn.run(app, host="0.0.0.0", port=port)
